# Cross-compile aria2 for aarch64 on x86_64 host
FROM ubuntu:22.04

ARG ARCH="aarch64"
ARG HOST="aarch64-linux-gnu"
#RUN sed -ie 's/archive\.ubuntu/cn.archive.ubuntu/g' /etc/apt/sources.list

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y --no-install-recommends apt-utils

RUN DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y --no-install-recommends \
        build-essential git curl ca-certificates \
        libxml2-dev libcppunit-dev autoconf automake autotools-dev autopoint libtool pkg-config \
        gcc-${HOST} g++-${HOST} && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /build

ARG CRUL_FLAG='-w "%{url}\n" --connect-timeout 10 --retry 5'
ARG PREFIX=/build/deps-${HOST}

ARG ZLIB_VERSION=1.3.1
RUN curl ${CRUL_FLAG} -L -O https://github.com/madler/zlib/releases/download/v${ZLIB_VERSION}/zlib-${ZLIB_VERSION}.tar.gz && \
    tar xf zlib-${ZLIB_VERSION}.tar.gz --no-same-owner && \
    cd zlib-${ZLIB_VERSION} && \
    CC=${HOST}-gcc \
    AR=${HOST}-ar \
    RANLIB=${HOST}-ranlib \
    ./configure \
        --prefix=${PREFIX} \
        --static && \
    make -j$(nproc) && \
    make install DESTDIR=

ARG OPENSSL_VERSION=3.0.18
RUN curl ${CRUL_FLAG} -L -O https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz && \
    tar xf openssl-${OPENSSL_VERSION}.tar.gz --no-same-owner && \
    cd openssl-${OPENSSL_VERSION} && \
    ./Configure linux-aarch64 \
        --cross-compile-prefix=${HOST}- \
        --prefix=${PREFIX} \
        no-shared \
        no-module \
        enable-legacy \
        no-tests && \
    make -j$(nproc) && \
    make install_sw

ARG LIBSSH2_VERSION=1.11.1
RUN curl ${CRUL_FLAG} -L -O https://libssh2.org/download/libssh2-${LIBSSH2_VERSION}.tar.bz2 && \
    tar xf libssh2-${LIBSSH2_VERSION}.tar.bz2 --no-same-owner && \
    cd libssh2-${LIBSSH2_VERSION} && \
    PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig:${PREFIX}/lib64/pkgconfig" \
    ./configure \
        --host=${HOST} \
        --build=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE) \
        --disable-shared \
        --enable-static \
        --prefix=${PREFIX} \
        --with-crypto=openssl \
        --with-libssl-prefix=${PREFIX} \
        --with-libz-prefix=${PREFIX} \
        CPPFLAGS="-I${PREFIX}/include" \
        LDFLAGS="-L${PREFIX}/lib -L${PREFIX}/lib64" && \
    make -j$(nproc) install

ARG EXPAT_RELEASE=R_2_7_3
ARG EXPAT_VERSION=2.7.3
RUN curl ${CRUL_FLAG} -L -O https://github.com/libexpat/libexpat/releases/download/${EXPAT_RELEASE}/expat-${EXPAT_VERSION}.tar.bz2 && \
    tar xf expat-${EXPAT_VERSION}.tar.bz2 --no-same-owner && \
    cd expat-${EXPAT_VERSION} && \
    ./configure \
        --host=${HOST} \
        --build=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE) \
        --disable-shared \
        --enable-static \
        --prefix=${PREFIX} && \
    make -j$(nproc) install

ARG SQLITE_VERSION=3510100
RUN curl ${CRUL_FLAG} -L -O https://www.sqlite.org/2025/sqlite-autoconf-${SQLITE_VERSION}.tar.gz && \
    tar xf sqlite-autoconf-${SQLITE_VERSION}.tar.gz --no-same-owner && \
    cd sqlite-autoconf-${SQLITE_VERSION} && \
    ./configure \
        --host=${HOST} \
        --build=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE) \
        --disable-shared \
        --enable-static \
        --prefix=${PREFIX} && \
    make -j$(nproc) install

ARG C_ARES_VERSION=1.34.6
RUN curl ${CRUL_FLAG} -L -O https://github.com/c-ares/c-ares/releases/download/v${C_ARES_VERSION}/c-ares-${C_ARES_VERSION}.tar.gz && \
    tar xf c-ares-${C_ARES_VERSION}.tar.gz --no-same-owner && \
    cd c-ares-${C_ARES_VERSION} && \
    ./configure \
        --host=${HOST} \
        --build=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE) \
        --disable-shared \
        --disable-tests \
        --enable-static \
        --without-random \
        --prefix=${PREFIX} && \
    make -j$(nproc) install

ARG JEMALLOC_VERSION=5.3.0
RUN curl ${CRUL_FLAG} -L -O https://github.com/jemalloc/jemalloc/releases/download/${JEMALLOC_VERSION}/jemalloc-${JEMALLOC_VERSION}.tar.bz2 && \
    tar xf jemalloc-${JEMALLOC_VERSION}.tar.bz2 --no-same-owner && \
    cd jemalloc-${JEMALLOC_VERSION} && \
    ./configure \
        --host=${HOST} \
        --build=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE) \
        --prefix=${PREFIX} \
        --enable-static \
        --disable-shared \
        --disable-prof \
        --disable-stats && \
    make -j$(nproc) install

ARG ARIA2_VERSION=1.37.0
RUN curl ${CRUL_FLAG} -L -O https://github.com/aria2/aria2/releases/download/release-${ARIA2_VERSION}/aria2-${ARIA2_VERSION}.tar.gz && \
    tar xf aria2-${ARIA2_VERSION}.tar.gz --no-same-owner && \
    cd aria2-${ARIA2_VERSION} && \
    ./configure \
        --host=${HOST} \
        --build=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE) \
        --prefix=/usr \
        --without-included-gettext \
        --disable-nls \
        --disable-shared \
        --with-libcares \
        --without-gnutls \
        --with-openssl \
        --with-sqlite3 \
        --without-libxml2 \
        --with-libexpat \
        --with-libz \
        --without-libgmp \
        --with-libssh2 \
        --with-jemalloc \
        --without-libgcrypt \
        --without-libnettle \
        ARIA2_STATIC=yes \
        CPPFLAGS="-I${PREFIX}/include" \
        LDFLAGS="-L${PREFIX}/lib -L${PREFIX}/lib64" \
        PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig:${PREFIX}/lib64/pkgconfig" && \
    make -j$(nproc) && \
    ${HOST}-strip src/aria2c && \
    make install DESTDIR=/output && \
    rm -rf /build/*